# Generated by Django 2.0.7 on 2018-10-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seoul', '0002_auto_20181027_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['fr_code']},
        ),
        migrations.AddField(
            model_name='spot',
            name='station',
            field=models.ForeignKey(default='T123', on_delete=django.db.models.deletion.CASCADE, to='seoul.Station'),
        ),
    ]
