# Generated by Django 2.0.7 on 2018-10-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoul', '0003_auto_20181027_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line_num',
            field=models.CharField(choices=[('1', '1호선'), ('2', '2호선'), ('3', '3호선'), ('4', '4호선'), ('5', '5호선'), ('6', '6호선'), ('7', '7호선'), ('8', '8호선'), ('9', '9호선'), ('A', '공항철도'), ('B', '분당선'), ('E', '전대에버라인'), ('G', '경춘선'), ('I', '인천1호선'), ('I2', '인천2호선'), ('K', '경의중앙선'), ('KK', '경강선'), ('S', '신분당선'), ('SU', '수인선'), ('T', '테스트'), ('U', '의정부경전철'), ('UI', '우이신설선')], max_length=3),
        ),
    ]
