# Generated by Django 2.1.2 on 2018-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoul', '0008_auto_20181101_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
