# Generated by Django 2.1.2 on 2018-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoul', '0010_auto_20181101_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
    ]
